python:
  env: "/opt/aux-venv"

output:
  directory: "/output-data"

secrets:
  access: "<access_token_secret>"

admin:
  public_key: "cDGjkkwr6kQP9zysF3qn1b648M3nd3npWV-HmxhO8i0"

databases:
  - name: "Example DB"
    tech: "PostgreSQL"
    vars:
      - example_db_name: "postgres"
      - example_db_user: "postgres"
      - example_db_password: "some-pass"
      - example_db_host: "postgres"
      - example_db_port: 5432
