python:
  env: "/opt/aux-venv"

output:
  directory: "/spark-data"

secrets:
  access: "<access_token_secret>"
  service: "<service_token_secret>"

spark:
  host: "spark-master"
  port: 7077

databases:
  - name: "Prices DB"
    tech: "PostgreSQL"
    vars:
      - test_db1_name: "sparkdb"
      - test_db1_user: "sparkuser"
      - test_db1_password: "sparkpass"
      - test_db1_host: "postgres"
      - test_db1_port: 5432

  - name: "Shop sales DB"
    tech: "PostgreSQL"
    vars:
      - test_db2_name: "postgres"
      - test_db2_user: "postgres"
      - test_db2_password: "gURH%gaNczV$WfcwGj(gQ"
      - test_db2_host: "online-retail-test.cv62km2c08to.eu-north-1.rds.amazonaws.com"
      - test_db2_port: 5432

  - name: "Programmatic DB"
    tech: "MySQL"
    vars:
      - test_db3_name: "brave_new"
      - test_db3_user: "highkick"
      - test_db3_password: "g29Zl5VxT7QcHKsR01G"
      - test_db3_host: "88.214.193.70"
      - test_db3_port: 3306
