python:
  env: "/opt/aux-venv"

output:
  directory: "/spark-data"

secrets:
  access: "<access_token_secret>"
  service: "<service_token_secret>"

spark:
  host: "spark-master"
  port: 7077

databases:
  - name: "Prices DB"
    tech: "PostgreSQL"
    vars:
      - test_db1_name: "sparkdb"
      - test_db1_user: "sparkuser"
      - test_db1_password: "sparkpass"
      - test_db1_host: "postgres"
      - test_db1_port: 5432

