python:
  env: "/Users/leonid/Documents/test/highkick/venv"

output:
  directory: "/Users/leonid/Documents/test/highkick/data"

secrets:
  access: "<access_token_secret>"
  service: "<service_token_secret>"

spark:
  host: "localhost"
  port: 7077

databases:
  - name: "Prices DB"
    tech: "PostgreSQL"
    vars:
      - test_db1_name: "sparkdb"
      - test_db1_user: "sparkuser"
      - test_db1_password: "sparkpass"
      - test_db1_host: "localhost"
      - test_db1_port: 9432

