python:
  env: "/Users/leonid/Documents/test/highkick/venv"

output:
  directory: "/Users/leonid/Documents/test/highkick/data"

secrets:
  access: "<access_token_secret>"
  service: "<service_token_secret>"

spark:
  host: "localhost"
  port: 7077

databases:
  - name: "UsersDB"
    tech: "PostgreSQL"
    vars:
      - test_db1_name: "sparkdb"
      - test_db1_user: "sparkuser"
      - test_db1_password: "sparkpass"
      - test_db1_host: "postgres"
      - test_db1_port: 5432

  - name: "DashboardsDB"
    tech: "PostgreSQL"
    vars:
      - test_db2_name: "sparkdb_dashboards"
      - test_db2_user: "sparkuser"
      - test_db2_password: "sparkpass"
      - test_db2_host: "postgres"
      - test_db2_port: 5432
