python:
  env: "/Users/leonid/Documents/test/highkick/venv"

secrets:
  access: "<access_token_secret>"
  service: "<service_token_secret>"

spark:
  host: "localhost"
  port: 7077

databases:
  - name: "UsersDB"
    tech: "PostgreSQL"
    vars:
      - test_db_name: "sparkdb"
      - test_db_user: "sparkuser"
      - test_db_password: "sparkpass"
      - test_db_host: "postgres"
      - test_db_port: 5432
